/*
 * Strava API v3
 *
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

// A row in a segment leaderboard
type SegmentLeaderboardEntry struct {
	// The public name of the athlete
	AthleteName string `json:"athlete_name,omitempty"`
	// The elapsed of the segment effort associated with this entry
	ElapsedTime int32 `json:"elapsed_time,omitempty"`
	// The moving of the segment effort associated with this entry
	MovingTime int32 `json:"moving_time,omitempty"`
	// The time at which the effort was started.
	StartDate time.Time `json:"start_date,omitempty"`
	// The time at which the effort was started in the local timezone.
	StartDateLocal time.Time `json:"start_date_local,omitempty"`
	// The rank of this entry in the leaderboard
	Rank int32 `json:"rank,omitempty"`
}
